#
# Talismans
# by Auxilor
#

crafting:
  discover: true # If players should automatically have recipes added to their crafting table.

read-inventory: true # If a player's inventory should be checked for talismans
read-enderchest: true # If a player's ender chest should be checked for talismans
read-shulkerboxes: true # If a player's shulker boxes should be checked for talismans
top-level-only: true # If only the top level of any given talisman should be activated

offhand-only: false # If talismans or shulkers of talismans need to be in the offhand to work

bag:
  title: "Talisman Bag (%page%/%pages%)"
  blocked-item: black_stained_glass_pane name:"&cYour talisman bag is not big enough!"
  blocked-item-lore: [ ]
  filler-item: gray_stained_glass_pane name:"&7"
  previous-page:
    item: arrow name:"&ePrevious Page"
    lore:
      - "&7Click to go to the previous page"
    no-page-item: barrier name:"&cNo Previous Page"
  next-page:
    item: arrow name:"&eNext Page"
    lore:
      - "&7Click to go to the next page"
    no-page-item: barrier name:"&cNo Next Page"
  close:
    item: barrier name:"&cClose"
    lore:
      - "&7Click to close the bag"
